/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Student, CorrectionRequest } from "./types";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "0081234567",
    personal: {
      namaLengkap: "Rian Hidayat Siregar",
      namaPanggilan: "Rian",
      nis: "221001",
      nisn: "0081234567",
      jenisKelamin: "Laki-laki",
      tempatLahir: "Medan",
      tanggalLahir: "2010-04-12",
      agama: "Islam",
      kewarganegaraan: "WNI",
      anakKe: 1,
      saudaraKandung: 2,
      saudaraTiri: 0,
      saudaraAngkat: 0,
      statusKeluarga: "Lengkap",
      bahasaSehariHari: "Bahasa Indonesia",
    },
    address: {
      alamatLengkap: "Jl. Merdeka No. 15, RT 02/RW 04, Kelurahan Padang Bulan, Kecamatan Medan Baru, Kota Medan",
      telepon: "081234567890",
      tinggalDengan: "Orang Tua",
      jarakKeSekolah: "2.5",
      transportasi: "Sepeda Motor",
    },
    health: {
      golonganDarah: "O",
      penyakitPernahDiderita: "Demam Berdarah (Umur 8 Tahun)",
      kelainanJasmani: "Tidak ada",
      tinggiBadan: 168,
      beratBadan: 58,
    },
    education: {
      lulusanDari: "SMP Negeri 1 Medan",
      tanggalIjazah: "2025-06-15",
      nomorIjazah: "DN-01/DI/0056782",
    },
    parents: {
      ayah: {
        nama: "Ahmad Fauzi Siregar",
        agama: "Islam",
        kewarganegaraan: "WNI",
        pendidikan: "S1 Teknik Sipil",
        pekerjaan: "Karyawan Swasta",
        penghasilan: "Rp 5.000.000 - Rp 10.000.000",
        alamat: "Jl. Merdeka No. 15, Kota Medan",
        telepon: "081234567891",
        isMasihHidup: true,
      },
      ibu: {
        nama: "Dewi Safitri",
        agama: "Islam",
        kewarganegaraan: "WNI",
        pendidikan: "D3 Akuntansi",
        pekerjaan: "Ibu Rumah Tangga",
        penghasilan: "Tidak Berpenghasilan",
        alamat: "Jl. Merdeka No. 15, Kota Medan",
        telepon: "085298765432",
        isMasihHidup: true,
      }
    },
    guardian: {
      hasWali: false,
      nama: "",
      agama: "",
      kewarganegaraan: "",
      pendidikan: "",
      pekerjaan: "",
      penghasilan: "",
      alamat: "",
      telepon: "",
      hubunganSiswa: "",
    },
    school: {
      kelasSkarang: "X-A",
      programKeahlian: "MIPA (Matematika dan IPA)",
      tanggalMasuk: "2025-07-10",
      beasiswa: "Beasiswa Prestasi Olahraga (Futsal)",
      nomorStb: "BI-2025-001",
    },
    // Default placeholder or generic avatar loaded by rendering engine based on gender
  },
  {
    id: "0098765432",
    personal: {
      namaLengkap: "Siti Rahmawati Salsabila",
      namaPanggilan: "Siti",
      nis: "212003",
      nisn: "0098765432",
      jenisKelamin: "Perempuan",
      tempatLahir: "Bandung",
      tanggalLahir: "2009-08-25",
      agama: "Islam",
      kewarganegaraan: "WNI",
      anakKe: 2,
      saudaraKandung: 1,
      saudaraTiri: 0,
      saudaraAngkat: 0,
      statusKeluarga: "Lengkap",
      bahasaSehariHari: "Sunda & Indonesia",
    },
    address: {
      alamatLengkap: "Gg. H. Samsudin No. 42, RT 01/RW 03, Kelurahan Dago, Kecamatan Coblong, Kota Bandung",
      telepon: "087823450981",
      tinggalDengan: "Orang Tua",
      jarakKeSekolah: "1.2",
      transportasi: "Angkutan Umum",
    },
    health: {
      golonganDarah: "A",
      penyakitPernahDiderita: "Asma Ringan (Terkontrol)",
      kelainanJasmani: "Tidak ada",
      tinggiBadan: 158,
      beratBadan: 46,
    },
    education: {
      lulusanDari: "SMP Negeri 5 Bandung",
      tanggalIjazah: "2024-06-12",
      nomorIjazah: "DN-02/DI/0049923",
    },
    parents: {
      ayah: {
        nama: "Yusuf Supriatna",
        agama: "Islam",
        kewarganegaraan: "WNI",
        pendidikan: "SMA",
        pekerjaan: "Wiraswasta (Toko Kelontong)",
        penghasilan: "Rp 3.000.000 - Rp 5.000.000",
        alamat: "Gg. H. Samsudin No. 42, Bandung",
        telepon: "087823450980",
        isMasihHidup: true,
      },
      ibu: {
        nama: "Aminah Kurnia",
        agama: "Islam",
        kewarganegaraan: "WNI",
        pendidikan: "SMA",
        pekerjaan: "Wiraswasta",
        penghasilan: "Rp 1.000.000 - Rp 3.000.000",
        alamat: "Gg. H. Samsudin No. 42, Bandung",
        telepon: "085311223344",
        isMasihHidup: true,
      }
    },
    guardian: {
      hasWali: false,
      nama: "",
      agama: "",
      kewarganegaraan: "",
      pendidikan: "",
      pekerjaan: "",
      penghasilan: "",
      alamat: "",
      telepon: "",
      hubunganSiswa: "",
    },
    school: {
      kelasSkarang: "XI-B",
      programKeahlian: "IPS (Ilmu Pengetahuan Sosial)",
      tanggalMasuk: "2024-07-15",
      beasiswa: "-",
      nomorStb: "BI-2024-045",
    },
  },
  {
    id: "0071112223",
    personal: {
      namaLengkap: "Andi Wijaya Kusuma",
      namaPanggilan: "Andi",
      nis: "203004",
      nisn: "0071112223",
      jenisKelamin: "Laki-laki",
      tempatLahir: "Surabaya",
      tanggalLahir: "2008-01-05",
      agama: "Kristen",
      kewarganegaraan: "WNI",
      anakKe: 3,
      saudaraKandung: 2,
      saudaraTiri: 0,
      saudaraAngkat: 0,
      statusKeluarga: "Lengkap",
      bahasaSehariHari: "Jawa & Indonesia",
    },
    address: {
      alamatLengkap: "Perumahan Indah Permai Blok C-10, RT 05/RW 10, Kelurahan Rungkut Kidul, Kota Surabaya",
      telepon: "081299887766",
      tinggalDengan: "Wali (Paman)",
      jarakKeSekolah: "5.0",
      transportasi: "Ojek Online",
    },
    health: {
      golonganDarah: "B",
      penyakitPernahDiderita: "Tidak ada",
      kelainanJasmani: "Menggunakan Kacamata (+1.5)",
      tinggiBadan: 172,
      beratBadan: 64,
    },
    education: {
      lulusanDari: "SMP Katolik Petra Surabaya",
      tanggalIjazah: "2023-06-18",
      nomorIjazah: "DN-05/DI/0023451",
    },
    parents: {
      ayah: {
        nama: "Hermawan Kusuma",
        agama: "Kristen",
        kewarganegaraan: "WNI",
        pendidikan: "S1 Ekonomi",
        pekerjaan: "Wafat",
        penghasilan: "-",
        alamat: "-",
        telepon: "-",
        isMasihHidup: false,
      },
      ibu: {
        nama: "Ratna Sari",
        agama: "Kristen",
        kewarganegaraan: "WNI",
        pendidikan: "S1 Hukum",
        pekerjaan: "PNS Pemkot Surabaya",
        penghasilan: "Rp 5.000.000 - Rp 10.000.000",
        alamat: "Perumahan Indah Permai Blok C-10, Surabaya",
        telepon: "081233445566",
        isMasihHidup: true,
      }
    },
    guardian: {
      hasWali: true,
      nama: "Budi Santoso",
      agama: "Kristen",
      kewarganegaraan: "WNI",
      pendidikan: "D3 Teknik",
      pekerjaan: "Wiraswasta",
      penghasilan: "Rp 3.000.000 - Rp 5.000.000",
      alamat: "Perumahan Indah Permai Blok C-10, Surabaya",
      telepon: "081344556677",
      hubunganSiswa: "Paman (Kakak Kandung Ibu)",
    },
    school: {
      kelasSkarang: "XII-C",
      programKeahlian: "Bahasa & Budaya",
      tanggalMasuk: "2023-07-12",
      beasiswa: "Beasiswa Pendidikan Pemkot",
      nomorStb: "BI-2023-089",
    },
  },
];

export const INITIAL_CORRECTION_REQUESTS: CorrectionRequest[] = [
  {
    id: "req-001",
    studentId: "0098765432",
    studentNisn: "0098765432",
    studentNama: "Siti Rahmawati Salsabila",
    requestDate: "2026-05-25 14:30",
    fieldName: "health.penyakitPernahDiderita",
    fieldLabel: "Keterangan Kesehatan (Penyakit)",
    oldValue: "Asma Ringan (Terkontrol)",
    newValue: "Asma Ringan (Sembuh) & Alergi Seafood",
    status: "Diproses",
  },
  {
    id: "req-002",
    studentId: "0081234567",
    studentNisn: "0081234567",
    studentNama: "Rian Hidayat Siregar",
    requestDate: "2026-05-24 09:15",
    fieldName: "personal.namaPanggilan",
    fieldLabel: "Nama Panggilan",
    oldValue: "Rian",
    newValue: "Rian Siregar",
    status: "Disetujui",
    notes: "Sudah disetujui, nama panggilan diperbarui.",
  }
];
